#!/usr/bin/env sh

# sudo without password for yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# settings
yabai -m config                                           \
    layout                     bsp            \
    window_shadow              off            \
    window_opacity             on             \
    window_opacity_duration    0.2            \
    active_window_opacity      1.0            \
    normal_window_opacity      0.85           \
    window_animation_duration  0              \
    window_animation_easing    ease_out_quint \
    mouse_follows_focus        on             \
    focus_follows_mouse        on             \
    split_ratio                0.50           \
    auto_balance               off            \
    mouse_modifier             alt            \
    mouse_action1              move           \
    mouse_action2              resize         \
    mouse_drop_action          swap           \
    top_padding                8              \
    bottom_padding             8              \
    left_padding               8              \
    right_padding              8              \
    window_gap                 8

# signals
yabai -m signal --add event=window_created action="yabai -m window --focus \$YABAI_WINDOW_ID"

# rules
yabai -m rule --add app="Visual Studio Code" space=1
yabai -m rule --add app="Cursor" space=2
yabai -m rule --add app="^Finder$" manage=on space=5
yabai -m rule --add app="Preview" space=5
yabai -m rule --add app="Cork" space=5
yabai -m rule --add app="WezTerm" space=6
yabai -m rule --add app="Warp" space=6
yabai -m rule --add app="^Obsidian$" manage=on space=6
yabai -m rule --add app="Brave Browser" space=7
yabai -m rule --add app="ChatGPT" space=8
yabai -m rule --add app="Safari" space=9
yabai -m rule --add app="MongoDB Compass" space=9
yabai -m rule --add app="Spotify" space=10


yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^iPone Mirroring$" manage=off
yabai -m rule --add app="^Trash$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="Logi Options+" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off

